import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
test.beforeEach(async({page})=>{await page.addInitScript(()=>{Object.defineProperty(window,'DeviceMotionEvent',{configurable:true,value:function DeviceMotionEvent(){}});Object.defineProperty(window,'DeviceOrientationEvent',{configurable:true,value:function DeviceOrientationEvent(){}});});});
test('records after permission, saves in batches, exports and replays a pickup recording',async({page})=>{
 await page.setViewportSize({width:390,height:844});
 const requests:{path:string;body:Record<string,unknown>}[]=[];
 await page.route('**/v1/sessions**',async route=>{requests.push({path:new URL(route.request().url()).pathname,body:route.request().postDataJSON()});await route.fulfill({status:200,contentType:'application/json',body:route.request().url().endsWith('/v1/sessions') ? '{"id":"test-server"}' : '{}'});});
 await page.goto('/');await expect(page.getByRole('checkbox')).not.toBeChecked();expect(requests).toHaveLength(0);
 await page.getByRole('button',{name:'Enable Sensors',exact:true}).click();await page.getByRole('button',{name:'pickup',exact:true}).click();await page.getByRole('button',{name:'Start Recording',exact:true}).click();
 await page.evaluate(()=>{for(let i=0;i<205;i++)window.dispatchEvent(Object.assign(new Event('devicemotion'),{acceleration:{x:2,y:0,z:0},accelerationIncludingGravity:{x:2,y:0,z:9.8},rotationRate:{alpha:0,beta:0,gamma:0},interval:16}));});
 await expect(page.getByText(/205 samples/)).toBeVisible();expect(requests).toHaveLength(0);
 await page.getByRole('button',{name:'Stop & Save',exact:true}).click();await expect(page.getByText(/Upload complete/)).toBeVisible();expect(requests[0]?.body.includeLocation).toBe(false);expect(requests[0]?.body.label).toBe('pickup');
 const batches=requests.filter(r=>r.path.endsWith('/records'));expect(batches.length).toBeGreaterThanOrEqual(2);expect((batches[0]!.body.records as unknown[]).length).toBe(200);expect(requests.at(-1)?.path).toContain('/finish');
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Download JSON',exact:true}).click();const downloaded=await downloadPromise;const path=await downloaded.path();const json=JSON.parse(await readFile(path!,'utf8'));expect(json.records.filter((r:{sensor:string})=>r.sensor==='motion')).toHaveLength(205);expect(json.records.some((r:{sensor:string})=>r.sensor==='location')).toBe(false);
 const records=[{sensor:'motion',t:0,data:{acceleration:{x:0,y:0,z:0}}},{sensor:'orientation',t:0,data:{alpha:0,beta:0,gamma:0,absolute:false}},{sensor:'motion',t:800,data:{acceleration:{x:0,y:0,z:0}}},{sensor:'motion',t:900,data:{acceleration:{x:2,y:0,z:0}}},{sensor:'motion',t:1100,data:{acceleration:{x:2,y:0,z:0}}},{sensor:'orientation',t:1200,data:{alpha:0,beta:45,gamma:0,absolute:false}},{sensor:'motion',t:1300,data:{acceleration:{x:0,y:0,z:0}}},{sensor:'motion',t:1500,data:{acceleration:{x:0,y:0,z:0}}}].map((r,i)=>({...r,seq:i,timestamp:10000+r.t,data:{...r.data,timestamp:10000+r.t,...(r.sensor==='motion'?{accelerationIncludingGravity:{x:0,y:0,z:9.8},rotationRate:{alpha:0,beta:0,gamma:0},interval:50}:{})}}));
 await page.getByRole('textbox',{name:'Recording JSON',exact:true}).fill(JSON.stringify({...json,startedAt:10000,endedAt:11500,records}));await page.getByRole('button',{name:'Load Recording',exact:true}).click();const count=requests.length;await page.getByRole('button',{name:'Replay',exact:true}).click();await expect(page.locator('.timeline')).toContainText('pickup score 0.80');expect(requests).toHaveLength(count);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:'/tmp/mobile-sensor-lab.png',fullPage:true});
});
test('failed upload retains exports and retries the existing session',async({page})=>{
 let fail=true,creates=0;
 await page.route('**/v1/sessions**',async route=>{const url=route.request().url();if(url.endsWith('/v1/sessions'))creates++;await route.fulfill({status:url.endsWith('/records')&&fail ? 503 : 200,contentType:'application/json',body:url.endsWith('/v1/sessions') ? '{"id":"retry"}' : '{}'});});
 await page.goto('/');await page.getByRole('button',{name:'Enable Sensors',exact:true}).click();await page.getByRole('button',{name:'Start Recording',exact:true}).click();await page.evaluate(()=>window.dispatchEvent(Object.assign(new Event('deviceorientation'),{alpha:0,beta:0,gamma:0,absolute:false})));await page.getByRole('button',{name:'Stop & Save',exact:true}).click();await expect(page.getByRole('alert')).toContainText('503');await expect(page.getByRole('button',{name:'Download JSON',exact:true})).toBeEnabled();fail=false;await page.getByRole('button',{name:'Retry / Upload session',exact:true}).click();await expect(page.getByText(/Upload complete/)).toBeVisible();expect(creates).toBe(1);
});
